# Build a service with environment variables
version: '1.0'

steps:
  build-example:
    type: build
    description: yaml example
    image-name: codefresh-io/${{IMAGE_NAME}}
    dockerfile: Dockerfile
    tag: latest
    environment:
      - PORT=9000
      - TEST=test
    variables:
      BITBUCKET_USERNAME: $BITBUCKET_USERNAME
      BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
      REPOSITORY: 'Inte-Github'
